/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package bonito;

import Entidades.Materia;
import java.awt.Color;
import javax.swing.JOptionPane;

public class GestionMaterias extends javax.swing.JDialog {

    private Materia busco;
    private boolean materiaEditada = false;
    private boolean salir = false;

    public GestionMaterias(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTNombre = new javax.swing.JTextField();
        jTAnio = new javax.swing.JTextField();
        jRBEstado = new javax.swing.JRadioButton();
        jBNuevo = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jBGuardar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jBSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jBBuscar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jBEditar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jTCodigo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBNuevo.setText("Nueva");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Codigo:");

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nombre:");

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Año:");

        jBBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LUPA.png"))); // NOI18N
        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Estado:");

        jBEditar.setText("Editar");
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBEstado)
                            .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBBuscar)
                        .addGap(15, 15, 15))))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jBNuevo)
                .addGap(10, 10, 10)
                .addComponent(jBEliminar)
                .addGap(10, 10, 10)
                .addComponent(jBEditar)
                .addGap(10, 10, 10)
                .addComponent(jBGuardar)
                .addGap(10, 10, 10)
                .addComponent(jBSalir)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jRBEstado))
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBNuevo)
                    .addComponent(jBEliminar)
                    .addComponent(jBGuardar)
                    .addComponent(jBSalir)
                    .addComponent(jBEditar))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        limpiarJt();
        bloquear(true);
        blkGuardar(true);
        jTCodigo.setEnabled(false);
        jRBEstado.setSelected(true);
        jRBEstado.setEnabled(false);
        blkEditar(false);
        blkEliminar(false);
        jBBuscar.setEnabled(false);
        salir = true;

    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        Object[] opciones = {"SI", "NO"};

        int opcion = JOptionPane.showOptionDialog(null,
                "¿Esta seguro de eliminar la materia?",
                "Confirmacion",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.YES_NO_OPTION,
                null, opciones, opciones[1]);

        if (opcion == JOptionPane.YES_OPTION) {
            Principal.controlMat.eliminarMateria(busco.getId());
            limpiarJt();
            blkEliminar(false);
            blkEditar(false);
            blkNuevo(true);

        } else if (opcion == JOptionPane.NO_OPTION) {
            limpiarJt();
            blkEliminar(false);
            blkEditar(false);
            blkNuevo(true);

        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        if (jTNombre.getText().isEmpty() || jTAnio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "todos los datos son obligatorios");
        } else {
            Object[] opciones = {"SI", "NO", "CANCELAR"};

            int opcion = JOptionPane.showOptionDialog(null,
                    "¿Todos los datos son Correctos?",
                    "Confirmacion",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.YES_NO_CANCEL_OPTION,
                    null, opciones, opciones[2]);
            //jRBEstado.setSelected(true);
            jRBEstado.setEnabled(false);

            if (opcion == JOptionPane.YES_OPTION) {
                if (materiaEditada) {
                    int idMat = Integer.parseInt(jTCodigo.getText());
                    int anio = Integer.parseInt(jTAnio.getText());
                    String nombre = jTNombre.getText();
                    boolean estado = jRBEstado.isSelected();
                    Materia nuevo = new Materia(idMat, nombre, anio, estado);
                    Principal.controlMat.modificarMateria(nuevo);
                    limpiarJt();
                    jTCodigo.setEnabled(true);
                    bloquear(false);
                    blkGuardar(false);
                    blkEditar(false);
                    blkNuevo(true);
                    salir = false;

                } else {
                    int anio = Integer.parseInt(jTAnio.getText());
                    String nombre = jTNombre.getText();
                    boolean estado = jRBEstado.isSelected();
                    Materia nuevo = new Materia(busco.getId(), nombre, anio, estado);
                    Principal.controlMat.modificarMateria(nuevo);
                    limpiarJt();
                    jTCodigo.setEnabled(true);
                    bloquear(false);
                    blkGuardar(false);

                }
            } else if (opcion == JOptionPane.NO_OPTION) {

            } else if (opcion == JOptionPane.CANCEL_OPTION) {
                limpiarJt();
                bloquear(false);
                blkGuardar(false);
                jTCodigo.setEnabled(true);
                blkNuevo(true);
                blkEditar(false);

            }
        }

    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        if (salir) {
            Object[] opciones = {"VOLVER", "SALIR"};
            int opcion = JOptionPane.showOptionDialog(null,
                    "¿Desea volver a Buscar?",
                    "Confirmacion",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.YES_NO_OPTION,
                    null, opciones, opciones[1]);
            if (opcion == JOptionPane.YES_OPTION) {
                limpiarJt();
                blkEliminar(false);
                blkEditar(false);
                blkNuevo(true);
                blkGuardar(false);
                bloquear(false);
                jBBuscar.setEnabled(true);
                jTCodigo.setEnabled(true);
                salir = false;
            } else {
                dispose();
            }
        } else {
            dispose();

        }
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed

        if (jTCodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No hay id de materia cargado");
        } else {
            int cod = Integer.parseInt(jTCodigo.getText());
            busco = Principal.controlMat.buscarMateria(cod);
            if (busco == null) {
                limpiarJt();
                blkEliminar(false);
                blkEditar(false);
                blkNuevo(true);
            } else {
                jTNombre.setText(busco.getNombre());
                int anio = busco.getAnio();
                jTAnio.setText("" + anio);
                jRBEstado.setSelected(busco.isEstado());
                blkEliminar(true);
                blkEditar(true);
                blkNuevo(true);
            }
        }

        //}
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        blkNuevo(false);
        blkEliminar(false);
        bloquear(true);
        blkGuardar(true);
        jTCodigo.setEnabled(false);
        materiaEditada = true;
        jRBEstado.setEnabled(true);

    }//GEN-LAST:event_jBEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestionMaterias dialog = new GestionMaterias(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRBEstado;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTAnio;
    private javax.swing.JTextField jTCodigo;
    private javax.swing.JTextField jTNombre;
    // End of variables declaration//GEN-END:variables
 public void limpiarJt() {
        
        jTNombre.setText("");
        jTAnio.setText("");
        jRBEstado.setSelected(false);
        jTCodigo.setText(null);
                
    }
    
    public void bloquear(boolean estado) {
        
        jTNombre.setEnabled(estado);
        jTAnio.setEnabled(estado);
        jRBEstado.setEnabled(estado);
        jTNombre.setDisabledTextColor(Color.BLACK);
        jTAnio.setDisabledTextColor(Color.BLACK);
                
    }
    
    public void blkEliminar(boolean estado) {
        
        jBEliminar.setEnabled(estado);
    }
    
    public void blkGuardar(boolean estado) {
        jBGuardar.setEnabled(estado);
    }
    
    public void blkEditar(boolean estado) {
        jBEditar.setEnabled(estado);
    }
    
    public void blkNuevo(boolean estado) {
        jBNuevo.setEnabled(estado);
    }
}
