/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bonito;

/**
 *
 * @author fernando
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        bMaterias = new javax.swing.JPanel();
        jLabelMaterias = new javax.swing.JLabel();
        bAlumno1 = new javax.swing.JPanel();
        jLabelAlumno1 = new javax.swing.JLabel();
        bAlumno2 = new javax.swing.JPanel();
        jLabelAlumno2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 500));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.jpeg"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 230, 170));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 193, 400, 10));

        jLabelMaterias.setFont(new java.awt.Font("Samanata", 1, 18)); // NOI18N
        jLabelMaterias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMaterias.setText("MATERIAS");
        jLabelMaterias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelMaterias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMateriasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bMateriasLayout = new javax.swing.GroupLayout(bMaterias);
        bMaterias.setLayout(bMateriasLayout);
        bMateriasLayout.setHorizontalGroup(
            bMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
            .addGroup(bMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bMateriasLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        bMateriasLayout.setVerticalGroup(
            bMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(bMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bMateriasLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(bMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 170, 50));

        jLabelAlumno1.setFont(new java.awt.Font("Samanata", 1, 18)); // NOI18N
        jLabelAlumno1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAlumno1.setText("ALUMNOS");
        jLabelAlumno1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelAlumno1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAlumno1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bAlumno1Layout = new javax.swing.GroupLayout(bAlumno1);
        bAlumno1.setLayout(bAlumno1Layout);
        bAlumno1Layout.setHorizontalGroup(
            bAlumno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
            .addGroup(bAlumno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bAlumno1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelAlumno1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        bAlumno1Layout.setVerticalGroup(
            bAlumno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(bAlumno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bAlumno1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelAlumno1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(bAlumno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 170, 50));

        jLabelAlumno2.setFont(new java.awt.Font("Samanata", 1, 18)); // NOI18N
        jLabelAlumno2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAlumno2.setText("ALUMNOS");
        jLabelAlumno2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelAlumno2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAlumno2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bAlumno2Layout = new javax.swing.GroupLayout(bAlumno2);
        bAlumno2.setLayout(bAlumno2Layout);
        bAlumno2Layout.setHorizontalGroup(
            bAlumno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bAlumno2Layout.createSequentialGroup()
                .addComponent(jLabelAlumno2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bAlumno2Layout.setVerticalGroup(
            bAlumno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelAlumno2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(bAlumno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 170, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMateriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMateriasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelMateriasMouseClicked

    private void jLabelAlumno1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAlumno1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelAlumno1MouseClicked

    private void jLabelAlumno2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAlumno2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelAlumno2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bAlumno1;
    private javax.swing.JPanel bAlumno2;
    private javax.swing.JPanel bMaterias;
    private javax.swing.JLabel jLabelAlumno1;
    private javax.swing.JLabel jLabelAlumno2;
    private javax.swing.JLabel jLabelMaterias;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
