/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bonito;

import AccesoADatos.AlumnoData;
import AccesoADatos.InscripcionData;
import AccesoADatos.MateriaData;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
/**
 *
 * @author fernando
 */
public class principal extends javax.swing.JFrame {

    public static AlumnoData controlAlu = new AlumnoData();
    public static MateriaData controlMat = new MateriaData();
    public static InscripcionData controlInsc = new InscripcionData();

    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        bAlumnos = new javax.swing.JPanel();
        jlAlumno = new javax.swing.JLabel();
        bMaterias = new javax.swing.JPanel();
        jlMateria = new javax.swing.JLabel();
        bGInscripciones1 = new javax.swing.JPanel();
        jlInscripcion = new javax.swing.JLabel();
        bGNotas1 = new javax.swing.JPanel();
        jlNota = new javax.swing.JLabel();
        bCalumnosXmateria = new javax.swing.JPanel();
        jlListarA = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        bSalir = new javax.swing.JPanel();
        jlSalir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(400, 500));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.jpeg"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 230, 170));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 400, 10));

        bAlumnos.setBackground(new java.awt.Color(2, 64, 125));
        bAlumnos.setForeground(new java.awt.Color(243, 162, 11));

        jlAlumno.setFont(new java.awt.Font("Pagul", 1, 24)); // NOI18N
        jlAlumno.setForeground(new java.awt.Color(255, 255, 255));
        jlAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlAlumno.setText("ALUMNO");
        jlAlumno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlAlumnoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlAlumnoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout bAlumnosLayout = new javax.swing.GroupLayout(bAlumnos);
        bAlumnos.setLayout(bAlumnosLayout);
        bAlumnosLayout.setHorizontalGroup(
            bAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        bAlumnosLayout.setVerticalGroup(
            bAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(bAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 170, 50));

        bMaterias.setBackground(new java.awt.Color(2, 64, 125));

        jlMateria.setFont(new java.awt.Font("Pagul", 1, 24)); // NOI18N
        jlMateria.setForeground(new java.awt.Color(255, 255, 255));
        jlMateria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMateria.setText("MATERIA");
        jlMateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlMateriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlMateriaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout bMateriasLayout = new javax.swing.GroupLayout(bMaterias);
        bMaterias.setLayout(bMateriasLayout);
        bMateriasLayout.setHorizontalGroup(
            bMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlMateria, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        bMateriasLayout.setVerticalGroup(
            bMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlMateria, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(bMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 170, 50));

        bGInscripciones1.setBackground(new java.awt.Color(2, 64, 125));

        jlInscripcion.setFont(new java.awt.Font("Pagul", 1, 20)); // NOI18N
        jlInscripcion.setForeground(new java.awt.Color(255, 255, 255));
        jlInscripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlInscripcion.setText("INSCRIPCIONES");
        jlInscripcion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlInscripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlInscripcionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlInscripcionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout bGInscripciones1Layout = new javax.swing.GroupLayout(bGInscripciones1);
        bGInscripciones1.setLayout(bGInscripciones1Layout);
        bGInscripciones1Layout.setHorizontalGroup(
            bGInscripciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlInscripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
        );
        bGInscripciones1Layout.setVerticalGroup(
            bGInscripciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlInscripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(bGInscripciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        bGNotas1.setBackground(new java.awt.Color(2, 64, 125));

        jlNota.setFont(new java.awt.Font("Pagul", 1, 20)); // NOI18N
        jlNota.setForeground(new java.awt.Color(255, 255, 255));
        jlNota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlNota.setText("NOTAS");
        jlNota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlNotaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlNotaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlNotaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout bGNotas1Layout = new javax.swing.GroupLayout(bGNotas1);
        bGNotas1.setLayout(bGNotas1Layout);
        bGNotas1Layout.setHorizontalGroup(
            bGNotas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlNota, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        bGNotas1Layout.setVerticalGroup(
            bGNotas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlNota, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(bGNotas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 170, 50));

        bCalumnosXmateria.setBackground(new java.awt.Color(2, 64, 125));

        jlListarA.setFont(new java.awt.Font("Pagul", 1, 20)); // NOI18N
        jlListarA.setForeground(new java.awt.Color(255, 255, 255));
        jlListarA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlListarA.setText("LISTAR ALUMNOS");
        jlListarA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlListarAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlListarAMouseExited(evt);
            }
        });

        javax.swing.GroupLayout bCalumnosXmateriaLayout = new javax.swing.GroupLayout(bCalumnosXmateria);
        bCalumnosXmateria.setLayout(bCalumnosXmateriaLayout);
        bCalumnosXmateriaLayout.setHorizontalGroup(
            bCalumnosXmateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlListarA, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );
        bCalumnosXmateriaLayout.setVerticalGroup(
            bCalumnosXmateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlListarA, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(bCalumnosXmateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 380, 50));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 193, 400, 10));

        bSalir.setBackground(new java.awt.Color(2, 64, 125));

        jlSalir.setFont(new java.awt.Font("Pagul", 1, 24)); // NOI18N
        jlSalir.setForeground(new java.awt.Color(255, 255, 255));
        jlSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSalir.setText("SALIR");
        jlSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout bSalirLayout = new javax.swing.GroupLayout(bSalir);
        bSalir.setLayout(bSalirLayout);
        bSalirLayout.setHorizontalGroup(
            bSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        bSalirLayout.setVerticalGroup(
            bSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(bSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 170, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlAlumnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlAlumnoMouseEntered
        jlAlumno.setForeground(new Color(222, 149, 21));
    }//GEN-LAST:event_jlAlumnoMouseEntered

    private void jlAlumnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlAlumnoMouseExited
        jlAlumno.setForeground(Color.WHITE);
    }//GEN-LAST:event_jlAlumnoMouseExited

    private void jlMateriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMateriaMouseEntered
        jlMateria.setForeground(new Color(222, 149, 21));
    }//GEN-LAST:event_jlMateriaMouseEntered

    private void jlInscripcionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlInscripcionMouseEntered
        jlInscripcion.setForeground(new Color(222, 149, 21));
    }//GEN-LAST:event_jlInscripcionMouseEntered

    private void jlNotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlNotaMouseEntered
        jlNota.setForeground(new Color(222, 149, 21));
    }//GEN-LAST:event_jlNotaMouseEntered

    private void jlListarAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlListarAMouseEntered
        jlListarA.setForeground(new Color(222, 149, 21));
    }//GEN-LAST:event_jlListarAMouseEntered

    private void jlSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSalirMouseEntered
        jlSalir.setForeground(new Color(222, 149, 21));
    }//GEN-LAST:event_jlSalirMouseEntered

    private void jlMateriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMateriaMouseExited
        jlMateria.setForeground(Color.WHITE);
    }//GEN-LAST:event_jlMateriaMouseExited

    private void jlInscripcionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlInscripcionMouseExited
        jlInscripcion.setForeground(Color.WHITE);
    }//GEN-LAST:event_jlInscripcionMouseExited

    private void jlNotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlNotaMouseExited
        jlNota.setForeground(Color.WHITE);
    }//GEN-LAST:event_jlNotaMouseExited

    private void jlListarAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlListarAMouseExited
        jlListarA.setForeground(Color.WHITE);
    }//GEN-LAST:event_jlListarAMouseExited

    private void jlSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSalirMouseExited
        jlSalir.setForeground(Color.WHITE);
    }//GEN-LAST:event_jlSalirMouseExited

    private void jlNotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlNotaMouseClicked
      notas nota = new notas(this, rootPaneCheckingEnabled);
      nota.setVisible(true);
      
    }//GEN-LAST:event_jlNotaMouseClicked

    private void jlSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSalirMouseClicked
     Object[] opciones = {"SI", "NO"};
     ImageIcon advertencia = new ImageIcon("/imagenes/advertencia.png");
        int opcion = JOptionPane.showOptionDialog(null,
            "¿Desea salir del sistema?",
            "Confirmacion",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.YES_NO_OPTION,
            advertencia, opciones, opciones[1]);
                        
            if (opcion == JOptionPane.YES_OPTION) {
                dispose();
            } else if (opcion == JOptionPane.NO_OPTION) {
          
            }        
    }//GEN-LAST:event_jlSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bAlumnos;
    private javax.swing.JPanel bCalumnosXmateria;
    private javax.swing.JPanel bGInscripciones1;
    private javax.swing.JPanel bGNotas1;
    private javax.swing.JPanel bMaterias;
    private javax.swing.JPanel bSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jlAlumno;
    private javax.swing.JLabel jlInscripcion;
    private javax.swing.JLabel jlListarA;
    private javax.swing.JLabel jlMateria;
    private javax.swing.JLabel jlNota;
    private javax.swing.JLabel jlSalir;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
