/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bonito;

import AccesoADatos.AlumnoData;
import AccesoADatos.InscripcionData;
import AccesoADatos.MateriaData;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import org.netbeans.lib.awtextra.*;

/**
 *
 * @author fernando
 */
public class Principal extends javax.swing.JFrame {

    public static AlumnoData controlAlu = new AlumnoData();
    public static MateriaData controlMat = new MateriaData();
    public static InscripcionData controlInsc = new InscripcionData();

    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jlInscripcion = new javax.swing.JLabel();
        jlNota = new javax.swing.JLabel();
        jlAlumno = new javax.swing.JLabel();
        jlMateria = new javax.swing.JLabel();
        jlListarA = new javax.swing.JLabel();
        jlSalir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ulpBanner.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 150));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 400, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 400, 10));

        jlInscripcion.setFont(new java.awt.Font("Pagul", 1, 20)); // NOI18N
        jlInscripcion.setForeground(new java.awt.Color(255, 255, 255));
        jlInscripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlInscripcion.setText("INSCRIPCIONES");
        jlInscripcion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlInscripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlInscripcionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlInscripcionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlInscripcionMouseExited(evt);
            }
        });
        jPanel1.add(jlInscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 171, 46));

        jlNota.setFont(new java.awt.Font("Pagul", 1, 20)); // NOI18N
        jlNota.setForeground(new java.awt.Color(255, 255, 255));
        jlNota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlNota.setText("NOTAS");
        jlNota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlNotaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlNotaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlNotaMouseExited(evt);
            }
        });
        jPanel1.add(jlNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 170, 50));

        jlAlumno.setFont(new java.awt.Font("Pagul", 1, 24)); // NOI18N
        jlAlumno.setForeground(new java.awt.Color(255, 255, 255));
        jlAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlAlumno.setText("ALUMNO");
        jlAlumno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlAlumnoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlAlumnoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlAlumnoMouseExited(evt);
            }
        });
        jPanel1.add(jlAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 170, 50));

        jlMateria.setFont(new java.awt.Font("Pagul", 1, 24)); // NOI18N
        jlMateria.setForeground(new java.awt.Color(255, 255, 255));
        jlMateria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMateria.setText("MATERIA");
        jlMateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMateriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlMateriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlMateriaMouseExited(evt);
            }
        });
        jPanel1.add(jlMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 170, 50));

        jlListarA.setFont(new java.awt.Font("Pagul", 1, 20)); // NOI18N
        jlListarA.setForeground(new java.awt.Color(255, 255, 255));
        jlListarA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlListarA.setText("LISTAR ALUMNOS");
        jlListarA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlListarAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlListarAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlListarAMouseExited(evt);
            }
        });
        jPanel1.add(jlListarA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 380, 50));

        jlSalir.setFont(new java.awt.Font("Pagul", 1, 24)); // NOI18N
        jlSalir.setForeground(new java.awt.Color(255, 255, 255));
        jlSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSalir.setText("SALIR");
        jlSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlSalirMouseExited(evt);
            }
        });
        jPanel1.add(jlSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 170, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlAlumnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlAlumnoMouseEntered
        jlAlumno.setForeground(new Color(222, 149, 21));
    }//GEN-LAST:event_jlAlumnoMouseEntered

    private void jlAlumnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlAlumnoMouseExited
        jlAlumno.setForeground(Color.WHITE);
    }//GEN-LAST:event_jlAlumnoMouseExited

    private void jlMateriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMateriaMouseEntered
        jlMateria.setForeground(new Color(222, 149, 21));
    }//GEN-LAST:event_jlMateriaMouseEntered

    private void jlInscripcionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlInscripcionMouseEntered
        jlInscripcion.setForeground(new Color(222, 149, 21));
    }//GEN-LAST:event_jlInscripcionMouseEntered

    private void jlNotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlNotaMouseEntered
        jlNota.setForeground(new Color(222, 149, 21));
    }//GEN-LAST:event_jlNotaMouseEntered

    private void jlListarAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlListarAMouseEntered
        jlListarA.setForeground(new Color(222, 149, 21));
    }//GEN-LAST:event_jlListarAMouseEntered

    private void jlSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSalirMouseEntered
        jlSalir.setForeground(new Color(222, 149, 21));
    }//GEN-LAST:event_jlSalirMouseEntered

    private void jlMateriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMateriaMouseExited
        jlMateria.setForeground(Color.WHITE);
    }//GEN-LAST:event_jlMateriaMouseExited

    private void jlInscripcionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlInscripcionMouseExited
        jlInscripcion.setForeground(Color.WHITE);
    }//GEN-LAST:event_jlInscripcionMouseExited

    private void jlNotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlNotaMouseExited
        jlNota.setForeground(Color.WHITE);
    }//GEN-LAST:event_jlNotaMouseExited

    private void jlListarAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlListarAMouseExited
        jlListarA.setForeground(Color.WHITE);
    }//GEN-LAST:event_jlListarAMouseExited

    private void jlSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSalirMouseExited
        jlSalir.setForeground(Color.WHITE);
    }//GEN-LAST:event_jlSalirMouseExited

    private void jlNotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlNotaMouseClicked
        Notas nota = new Notas(null, rootPaneCheckingEnabled);
        nota.setVisible(true);

    }//GEN-LAST:event_jlNotaMouseClicked

    private void jlSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSalirMouseClicked
        Object[] opciones = {"SI", "NO"};
        ImageIcon advertencia = new ImageIcon("/imagenes/advertencia.png");
        int opcion = JOptionPane.showOptionDialog(null,
                "¿Desea salir del sistema?",
                "Confirmacion",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.YES_NO_OPTION,
                advertencia, opciones, opciones[1]);

        if (opcion == JOptionPane.YES_OPTION) {
            dispose();
        } else if (opcion == JOptionPane.NO_OPTION) {

        }
    }//GEN-LAST:event_jlSalirMouseClicked

    private void jlAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlAlumnoMouseClicked
        GestionAlumnos alu = new GestionAlumnos(null, rootPaneCheckingEnabled);
        alu.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jlAlumnoMouseClicked

    private void jlMateriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMateriaMouseClicked
        GestionMaterias mate = new GestionMaterias(null, rootPaneCheckingEnabled);
        mate.setVisible(true);
    }//GEN-LAST:event_jlMateriaMouseClicked

    private void jlInscripcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlInscripcionMouseClicked
        InscripcionesForm insc = new InscripcionesForm(null, rootPaneCheckingEnabled);
        insc.setVisible(true);
    }//GEN-LAST:event_jlInscripcionMouseClicked

    private void jlListarAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlListarAMouseClicked
      ConsultaAlumnMate consultAlumno = new ConsultaAlumnMate(null, rootPaneCheckingEnabled);
      consultAlumno.setVisible(true);
    }//GEN-LAST:event_jlListarAMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jlAlumno;
    private javax.swing.JLabel jlInscripcion;
    private javax.swing.JLabel jlListarA;
    private javax.swing.JLabel jlMateria;
    private javax.swing.JLabel jlNota;
    private javax.swing.JLabel jlSalir;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
